const OPENINGS_EXACT_PATHS = new Set([
  '/',
  '/en',
  '/box-break',
  '/box-break/explorar',
  '/box-break/sessoes',
  '/rips',
  '/batches',
  '/batches/explorar',
  '/lives',
  '/openings',
  '/colecao',
  '/colecionador',
  '/item',
  '/explorar',
  '/japan-search',
  '/wishlist',
  '/aberturas',
  '/aberturas/explorar',
  '/minha-yuume/colecao',
  '/minha-yuume/wishlist',
  '/en/box-break',
  '/en/box-break/explore',
  '/en/box-break/sessions',
  '/en/rips',
  '/en/batches',
  '/en/batches/explore',
  '/en/lives',
  '/en/openings',
  '/en/collection',
  '/en/collector',
  '/en/item',
  '/en/explore',
  '/en/japan-search',
  '/en/wishlist',
  '/en/aberturas',
  '/en/aberturas/explorar',
  '/en/minha-yuume/colecao',
  '/en/minha-yuume/wishlist',
])

const OPENINGS_PREFIX_PATHS = [
  '/box-break/',
  '/rips/',
  '/batches/',
  '/lives/',
  '/openings/',
  '/colecao/',
  '/item/',
  '/explorar/',
  '/wishlist/',
  '/aberturas/',
  '/minha-yuume/colecao/',
  '/minha-yuume/wishlist/',
  '/en/box-break/',
  '/en/rips/',
  '/en/batches/',
  '/en/lives/',
  '/en/openings/',
  '/en/collection/',
  '/en/item/',
  '/en/explore/',
  '/en/wishlist/',
  '/en/aberturas/',
  '/en/minha-yuume/colecao/',
  '/en/minha-yuume/wishlist/',
]

export function isOpeningsPath(pathname = '') {
  const path = String(pathname || '').trim()
  if (OPENINGS_EXACT_PATHS.has(path)) return true
  return OPENINGS_PREFIX_PATHS.some((prefix) => path.startsWith(prefix))
}

